export const EXTRACT_SOURCES = [
  'CACHE',
  'JSON_LD',
  'SCHEMA_ORG_PRODUCT',
  'SCHEMA_ORG_PRODUCT_GROUP',
  'MICRODATA',
  'RDFA',
  'OPEN_GRAPH',
  'EMBEDDED_JSON',
  'PLATFORM_SHOPIFY',
  'PLATFORM_WOOCOMMERCE',
  'PLATFORM_MAGENTO',
  'PLATFORM_BIGCOMMERCE',
  'PLATFORM_SFCC',
  'PLAYWRIGHT_NETWORK',
  'PLAYWRIGHT_RENDERED_DOM',
  'PLAYWRIGHT_EMBEDDED_STATE',
  'AI_FALLBACK',
  'RYE_API',
  'DIFFBOT_API',
  'ZYTE_API',
  'BRIGHT_DATA_API',
  'NORMALIZER',
  'UNKNOWN'
] as const;

export type ExtractSource = (typeof EXTRACT_SOURCES)[number];

export const DETERMINISTIC_SOURCES = new Set<ExtractSource>([
  'JSON_LD',
  'SCHEMA_ORG_PRODUCT',
  'SCHEMA_ORG_PRODUCT_GROUP',
  'MICRODATA',
  'RDFA',
  'OPEN_GRAPH',
  'EMBEDDED_JSON',
  'PLATFORM_SHOPIFY',
  'PLATFORM_WOOCOMMERCE',
  'PLATFORM_MAGENTO',
  'PLATFORM_BIGCOMMERCE',
  'PLATFORM_SFCC',
  'PLAYWRIGHT_NETWORK',
  'PLAYWRIGHT_RENDERED_DOM',
  'PLAYWRIGHT_EMBEDDED_STATE'
]);
